"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 3

console_title_template = '{{ .Shell }} in {{ .Folder }}'

[palette]
  black = '#262B44'
  blue = '#4B95E9'
  green = '#59C9A5'
  orange = '#F07623'
  red = '#D81E5B'
  white = '#E0DEF4'
  yellow = '#F3AE35'
  os = '#E0DEF4'

[secondary_prompt]
  template = '<p:yellow,transparent></><,p:yellow> > </><p:yellow,transparent></> '
  foreground = 'p:black'
  background = 'transparent'

[transient_prompt]
  template = '<p:yellow,transparent></><,p:yellow> {{ .Folder }} </><p:yellow,transparent></> '
  foreground = 'p:black'
  background = 'transparent'

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '<background,transparent></>{{.Icon}} '
    foreground = "p:os"
    background = "#546E7A"
    type = "os"
    style = "plain"

  # [[blocks.segments]]
  #   template = '<parentBackground,background></> {{ if .SSHSession }} {{ end }}{{ .UserName }} '
  #   foreground = 'p:black'
  #   background = 'p:yellow'
  #   type = 'session'
  #   style = 'plain'

  [[blocks.segments]]
    template = '<parentBackground,background></>  {{ path .Path .Location }} '
    foreground = 'p:white'
    background = 'p:orange'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    template = '<parentBackground,background></> {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
    foreground = 'p:black'
    background = 'p:green'
    type = 'git'
    style = 'plain'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:black{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:white{{ end }}', '{{ if gt .Ahead 0 }}p:white{{ end }}']
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}', '{{ if gt .Ahead 0 }}#49416D{{ end }}', '{{ if gt .Behind 0 }}#7A306C{{ end }}']

    [blocks.segments.properties]
      branch_max_length = 25
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    template = '<parentBackground,background></>   '
    foreground = 'p:white'
    background = 'p:yellow'
    type = 'root'
    style = 'plain'

  [[blocks.segments]]
    template = '<parentBackground,background></> {{ if gt .Code 0 }}{{ else }}{{ end }} '
    foreground = 'p:white'
    background = 'p:blue'
    type = 'status'
    style = 'plain'
    background_templates = ['{{ if gt .Code 0 }}p:red{{ end }}']
    [blocks.segments.properties]
      always_enabled = true
  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    template = '<parentBackground,transparent></>'

[[blocks]]
  type = 'rprompt'

  [[blocks.segments]]
    template = " {{ .Full }} "
    foreground = "#f6553c"
    background = "transparent"
    type = "swift"
    style = "plain"

    [blocks.segments.properties]
      display_mode = 'files'
      home_enabled = false

  [[blocks.segments]]
    template = ' {{ .Full }} '
    foreground = 'p:green'
    background = 'transparent'
    type = 'node'
    style = 'plain'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_package_manager = false
      home_enabled = false

  [[blocks.segments]]
    template = "  {{ .Full }} "
    foreground = "#99908a"
    background = "transparent"
    type = "rust"
    style = "plain"

  [[blocks.segments]]
    template = ' '
    foreground = 'p:blue'
    background = 'transparent'
    type = 'go'
    style = 'plain'

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    template = ' '
    foreground = 'p:yellow'
    background = 'transparent'
    type = 'python'
    style = 'plain'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_version = false
      fetch_virtual_env = false

  [[blocks.segments]]
    template = 'in <p:blue><b>{{ .Name }}</b></> '
    foreground = 'p:white'
    background = 'transparent'
    type = 'shell'
    style = 'plain'

  [[blocks.segments]]
    template = 'at <p:blue><b>{{ .CurrentDate | date "15:04:05" }}</b></>'
    foreground = 'p:white'
    background = 'transparent'
    type = 'time'
    style = 'plain'

[[tooltips]]
  leading_diamond = ''
  trailing_diamond = ''
  template = '  {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} '
  foreground = 'p:white'
  background = 'p:orange'
  type = 'aws'
  style = 'diamond'
  tips = ['aws']

  [tooltips.properties]
    display_default = true

[[tooltips]]
  leading_diamond = ''
  trailing_diamond = ''
  template = '  {{ .Name }} '
  foreground = 'p:white'
  background = 'p:blue'
  type = 'az'
  style = 'diamond'
  tips = ['az']

  [tooltips.properties]
    display_default = true
